swagger: '2.0'
info:
  title: gcp-http-api
  description: Example HTTP API with GCP and Go 
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://hello-http-55wgnx34ra-uc.a.run.app
      responses:
        '200':
          description: A successful response
          schema:
            type: string
